import type {Metadata} from "next";

import "./globals.css";

import {Header} from "@/components/Header";

import {barlow_condensed, bellefair} from "./fonts";

export const metadata: Metadata = {
  title: "space-tourism-website",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html
      className={`${bellefair.variable} ${barlow_condensed.variable} bg-home_desktop bg-cover bg-center bg-no-repeat`}
      lang="en"
    >
      <body className="grid min-h-screen grid-rows-[auto,1fr,auto]">
        <Header />
        <main className="py-8">{children}</main>
        <footer className=" text-center leading-[3rem] opacity-70">
          © {new Date().getFullYear()} space-tourism-website
        </footer>
      </body>
    </html>
  );
}
